
services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest     
    container_name: redis_stack
    ports:
      - "6381:6379"                       
      - "8001:8001"                       
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
